### ISSUE TITLE
Secret Keys?

### ISSUE THREAD

**Issue by bendangelo** [justinthec/receiptsheep#1]
You sure you want this public?

https://github.com/justinthec/receiptsheep/blob/master/call.js#L19

**Comment by justinthec** [comment]
:+1: thanks Ben. I'll fix that after some sleep ha

**Comment by kyewei** [comment]
Not a big deal, these are keys for a sandbox environment, and can't do anything. 

Update: I've also deactivated them. So they literally can't do anything.

**Comment by bendangelo** [comment]
Ok I'm closing this then.
